- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: checking cities schema exists or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print schema output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: load cities schema
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql"
  when: schema.stdout != "1"